INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE AUDITORIA FINANCIERA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE AUDITORIA FINANCIERA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'SUBDIRECCION INVESTIGADORA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION INVESTIGADORA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE DENUNCIAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE DENUNCIAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'CONTRALORIA MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'CONTRALORIA MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'SUBDIRECCION DE CUMPLIMIENTO, CONTROL Y EVALUACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE CUMPLIMIENTO, CONTROL Y EVALUACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'SUBDDIRECCION DE AUDITORIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDDIRECCION DE AUDITORIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'SUBDIRECCION SUBSTANCIADORA Y RESOLUTORA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION SUBSTANCIADORA Y RESOLUTORA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE SEGUIMIENTO AL SISTEMA ANTICORRUPCION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SEGUIMIENTO AL SISTEMA ANTICORRUPCION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE AUDITORIA ADMINISTRATIVA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE AUDITORIA ADMINISTRATIVA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE SUBSTANCIACION Y NOTIFICACIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SUBSTANCIACION Y NOTIFICACIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE AUDITORIA DE OBRA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE AUDITORIA DE OBRA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CONTRALORIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE SITUACION PATRIMONIAL, DECLARACION DE INTERESES Y ENTREGA RECEPCION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SITUACION PATRIMONIAL, DECLARACION DE INTERESES Y ENTREGA RECEPCION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE PROTECCION ANIMAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROTECCION ANIMAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE BOMBEROS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BOMBEROS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE INSPECCION Y ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INSPECCION Y ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE CONTROL DE MONITOREO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONTROL DE MONITOREO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE NORMATIVIDAD AMBIENTAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE NORMATIVIDAD AMBIENTAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE ATENCION PREHOSPITALARIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ATENCION PREHOSPITALARIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE VIVERO MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE VIVERO MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE EDUCACION AMBIENTAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE EDUCACION AMBIENTAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE ATLAS Y GESTION INTEGRAL DE RIESGOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ATLAS Y GESTION INTEGRAL DE RIESGOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'SUBCOMANDANTE DE BOMBEROS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBCOMANDANTE DE BOMBEROS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'JEFATURA DE REHABILITACION Y ZONAS MINADAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'JEFATURA DE REHABILITACION Y ZONAS MINADAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'SUBDIRECCION DE BOMBEROS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE BOMBEROS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'SUBDIRECCION DE PROTECCION CIVIL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE PROTECCION CIVIL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'SUBDIRECCION DE MEDIO AMBIENTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE MEDIO AMBIENTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'COORDINACION MUNICIPAL DE PROTECCION CIVIL, BOMBEROS Y MEDIO AMBIENTE' LIMIT 1), 'DEPARTAMENTO DE CAPACITACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CAPACITACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'CUARTO REGIDOR' LIMIT 1), 'CUARTO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'CUARTO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DECIMO PRIMER REGIDOR' LIMIT 1), 'DECIMO PRIMER REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DECIMO PRIMER REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DECIMO REGIDOR' LIMIT 1), 'DECIMO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DECIMO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DECIMO SEGUNDO REGIDOR' LIMIT 1), 'DECIMO SEGUNDO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DECIMO SEGUNDO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS' LIMIT 1), 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS' LIMIT 1), 'COORDINACION DE INVESTIGACION Y POLITICAS PUBLICAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE INVESTIGACION Y POLITICAS PUBLICAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS' LIMIT 1), 'COORDINACION DE DIFUSION Y CAPACITACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE DIFUSION Y CAPACITACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DEFENSORIA MUNICIPAL DE DERECHOS HUMANOS' LIMIT 1), 'COORDINADOR ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINADOR ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE ALMACEN', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ALMACEN');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'COORDINADOR DE ENLACES ADMINISTRATIVOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINADOR DE ENLACES ADMINISTRATIVOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DIRECCION DE ADMINISTRACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE ADMINISTRACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SUBDIRECCION DE CONTROL VEHICULAR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE CONTROL VEHICULAR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE MANTENIMIENTO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MANTENIMIENTO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE ADMINISTRACION VEHICULAR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ADMINISTRACION VEHICULAR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SUBDIRECCION DE RECURSOS HUMANOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE RECURSOS HUMANOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE RELACIONES LABORALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE RELACIONES LABORALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE LOGISTICA Y EVENTOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE LOGISTICA Y EVENTOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE NOMINAS Y PAGOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE NOMINAS Y PAGOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO OPERATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO OPERATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE INFORMATICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INFORMATICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE ADQUISICIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ADQUISICIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SUBDIRECCION DE RECURSOS MATERIALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE RECURSOS MATERIALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE LICITACIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE LICITACIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SUBDIRECCION DE INFORMATICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE INFORMATICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE CAPACITACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CAPACITACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SUBDIRECCION DE SERVICIOS GENERALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE SERVICIOS GENERALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'ADMINISTRACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ADMINISTRACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'SECRETARIA TECNICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SECRETARIA TECNICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE ADMINISTRACION' LIMIT 1), 'DEPARTAMENTO DE INTENDENCIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INTENDENCIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'COORDINACION DE ATENCION EMPRESARIAL CAE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ATENCION EMPRESARIAL CAE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'DIRECCION DE DESARROLLO ECONOMICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE DESARROLLO ECONOMICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'DEPARTAMENTO DE SERVICIO MUNICIPAL DEL EMPLEO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SERVICIO MUNICIPAL DEL EMPLEO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'DEPARTAMENTO DE ECONOMIA SOCIAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ECONOMIA SOCIAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'SUBDIRECCION DE PROMOCION Y FOMENTO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE PROMOCION Y FOMENTO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'DEPRARTAMENTO DE FERIAS Y EVENTOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPRARTAMENTO DE FERIAS Y EVENTOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'UNIDAD DE DICTAMEN DE GIRO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE DICTAMEN DE GIRO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO ECONOMICO' LIMIT 1), 'COORDINACION DE OFICINA MUNICIPAL DE ENLACE PARA LA EMISION DE PASAPORTES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE OFICINA MUNICIPAL DE ENLACE PARA LA EMISION DE PASAPORTES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DIRECCION DE DESARROLLO SOCIAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE DESARROLLO SOCIAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE ATENCION A ORGANIZACIONES SOCIALES Y COMUNITARIAS (OSC)', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ATENCION A ORGANIZACIONES SOCIALES Y COMUNITARIAS (OSC)');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE DESARROLLO COMUNITARIO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE DESARROLLO COMUNITARIO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE PROMOCION Y DIFUSION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROMOCION Y DIFUSION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'SUBDIRECCION DE CULTURA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE CULTURA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'COORDINACION DE FOMENTO CULTURAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE FOMENTO CULTURAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'COORDINACION DE CULTURA FISICA Y DEPORTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE CULTURA FISICA Y DEPORTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE VINCULACION ESTATAL Y FEDERAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE VINCULACION ESTATAL Y FEDERAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'SUBDIRECCION DEL DEPORTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DEL DEPORTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE INFRAESTRUCTURA CULTURAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INFRAESTRUCTURA CULTURAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'SUBDIRECCION DE CONCERTACION SOCIAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE CONCERTACION SOCIAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'COORDINACION DE PROGRAMAS SOCIALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE PROGRAMAS SOCIALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'UNIDAD DEL INTERES SUPERIOR DE NIÑAS, NIÑOS Y ADOLESCENTES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DEL INTERES SUPERIOR DE NIÑAS, NIÑOS Y ADOLESCENTES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE DESARROLLO SOCIAL' LIMIT 1), 'DEPARTAMENTO DE INFRAESTRUCTURA DEPORTIVA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INFRAESTRUCTURA DEPORTIVA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE EDUCACION' LIMIT 1), 'DEPARTAMENTO DE BIBLIOTECAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BIBLIOTECAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE EDUCACION' LIMIT 1), 'DEPARTAMENTO DE BECAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BECAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE EDUCACION' LIMIT 1), 'DIRECCION DE EDUCACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE EDUCACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE EDUCACION' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE EDUCACION' LIMIT 1), 'COORDINACION DE ATENCION AL SECTOR EDUCATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ATENCION AL SECTOR EDUCATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DIRECCION DE INNOVACION Y COMUNICACIÓN', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'SUBDIRECCION DE COMUNICACION Y MEDIOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE COMUNICACION Y MEDIOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'COORDINACION DE ATENCION CIUDADANA Y VINCULACION DIGITAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ATENCION CIUDADANA Y VINCULACION DIGITAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DEPARTAMENTO DE DOCUMENTACION DE APLICACIONES Y SISTEMAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE DOCUMENTACION DE APLICACIONES Y SISTEMAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'COORDINACION DE COMUNICACION DIGITAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE COMUNICACION DIGITAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'SUBDIRECCION DE INNOVACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE INNOVACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'SUBDIRECCION DE GOBIERNO DIGITAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE GOBIERNO DIGITAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DEPARTAMENTO DE APLICACION DE ATENCION CIUDADANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE APLICACION DE ATENCION CIUDADANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'COORDINACION TECNICA DE PLANEACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION TECNICA DE PLANEACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DEPARTAMENTO DE COMUNICACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE COMUNICACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'COORDINACION DE IMPLEMENTACION DE APLICACIONES Y SISTEMAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE IMPLEMENTACION DE APLICACIONES Y SISTEMAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DEPARTAMENTO DE PROYECTOS DE GOBIERNO DIGITAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROYECTOS DE GOBIERNO DIGITAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE INNOVACION Y COMUNICACIÓN' LIMIT 1), 'DEPARTAMENTO DE MEDIOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MEDIOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE LA JUVENTUD' LIMIT 1), 'DIRECCION DE LA JUVENTUD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE LA JUVENTUD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE LA JUVENTUD' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE SERVICIOS FACULTATIVOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE SERVICIOS FACULTATIVOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'SUBDIRECCION OPERATIVA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION OPERATIVA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'CUARTEL GENERAL Y BANDA DE GUERRA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'CUARTEL GENERAL Y BANDA DE GUERRA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'JEFES DE SECTOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'JEFES DE SECTOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'SUBDIRECCION DE TRANSITO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE TRANSITO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE SUPERVISION GENERAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE SUPERVISION GENERAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE SERVICIO PROFESIONAL DE CARRERA Y FORMACION POLICIAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SERVICIO PROFESIONAL DE CARRERA Y FORMACION POLICIAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO C4', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO C4');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'SUBDIRECCION DE PREVENCION DEL DELITO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE PREVENCION DEL DELITO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'SUBDIRECCION JURIDICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION JURIDICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE ESCUADRON DE CABALLERIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ESCUADRON DE CABALLERIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'COMISION DE HONOR Y JUSTICIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COMISION DE HONOR Y JUSTICIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'SUBDIRECCION ADMINISTRATIVA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION ADMINISTRATIVA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE ARMAMENTO Y EQUIPO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ARMAMENTO Y EQUIPO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE VIALIDAD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE VIALIDAD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE OPERACIONES ESPECIALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE OPERACIONES ESPECIALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE PERSONAL ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PERSONAL ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE ANALISIS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ANALISIS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE INFORMACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INFORMACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE INVESTIGACION DEL DELITO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE INVESTIGACION DEL DELITO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'GRUPO DE OPERACIONES MOTORIZADO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'GRUPO DE OPERACIONES MOTORIZADO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE ALAMACEN Y BIENES MUEBLES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ALAMACEN Y BIENES MUEBLES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE PUESTAS A DISPOSICION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PUESTAS A DISPOSICION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE ASUNTOS INTERNOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE ASUNTOS INTERNOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE DISEÑO DE SECTORES Y CUADRANTES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE DISEÑO DE SECTORES Y CUADRANTES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE PREVENCION DEL DELITO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PREVENCION DEL DELITO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'UNIDAD DE INTELIGENCIA MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE INTELIGENCIA MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE INFRACCIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INFRACCIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SEGURIDAD PUBLICA Y TRANSITO MUNICIPAL' LIMIT 1), 'DEPARTAMENTO TECNICO OPERATIVO DE TRANSITO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO TECNICO OPERATIVO DE TRANSITO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE RECOLECCION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE RECOLECCION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE PARQUES, JARDINES Y ENCALADO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PARQUES, JARDINES Y ENCALADO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE BARRIDO ZONA SUR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BARRIDO ZONA SUR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO ZONA NORTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO ZONA NORTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO ZONA SUR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO ZONA SUR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE BARRIDO ZONA NORTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BARRIDO ZONA NORTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DIRECCION DE SERVICIOS PUBLICOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DE SERVICIOS PUBLICOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE PANTEONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PANTEONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE MOBILIARIO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MOBILIARIO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'SUBDIRECCION DE PARQUES, JARDINES, PANTEONES Y MOBILIARIO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE PARQUES, JARDINES, PANTEONES Y MOBILIARIO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'SUBDIRECCION GENERAL DE SERVICIOS PUBLICOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION GENERAL DE SERVICIOS PUBLICOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'SUBDIRECCION DE LIMPIA Y TRANSPORTE', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE LIMPIA Y TRANSPORTE');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'SUBDIRECCION DE ALUMBRADO PUBLICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE ALUMBRADO PUBLICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DE SERVICIOS PUBLICOS' LIMIT 1), 'DEPARTAMENTO DE DISPOSICION DE RESIDUOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE DISPOSICION DE RESIDUOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER' LIMIT 1), 'DEPARTAMENTO DE GESTION Y ATENCION A LA MUJER', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE GESTION Y ATENCION A LA MUJER');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER' LIMIT 1), 'DIRECCION DEL INSTITUTO DE LA MUJER', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER' LIMIT 1), 'DEPARTAMENTO DE PROGRAMAS INSTITUCIONALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROGRAMAS INSTITUCIONALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION DEL INSTITUTO DE LA MUJER' LIMIT 1), 'DEPARTAMENTO DE APOYO A EMPRENDEDORAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE APOYO A EMPRENDEDORAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE CONSERVACION DE INFRAESTRUCTURA PARA LA MOVILIDAD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONSERVACION DE INFRAESTRUCTURA PARA LA MOVILIDAD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE PROYECTOS DE MOVILIDAD E INFRAESTRUCTURA URBANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROYECTOS DE MOVILIDAD E INFRAESTRUCTURA URBANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE PROYECTOS DE EQUIPAMIENTO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROYECTOS DE EQUIPAMIENTO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE CONSTRUCCION Y REGULACION DE OBRAS DE MOVILIDAD E INFRAESTRUCTURA URBANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONSTRUCCION Y REGULACION DE OBRAS DE MOVILIDAD E INFRAESTRUCTURA URBANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE CONSERVACION DE EQUIPAMIENTO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONSERVACION DE EQUIPAMIENTO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DIRECCION GENERAL DE OBRAS PUBLICAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'SUBDIRECCION DE MOVILIDAD E INFRAESTRUCTURA URBANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE MOVILIDAD E INFRAESTRUCTURA URBANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE CONSTRUCCION Y REGULACION DE OBRAS DE EQUIPAMIENTO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONSTRUCCION Y REGULACION DE OBRAS DE EQUIPAMIENTO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE CONTROL PRESUPUESTAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONTROL PRESUPUESTAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'SUBDIRECCION DE GESTION Y CONTROL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE GESTION Y CONTROL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'COORDINACION TECNICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION TECNICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE ATENCION DE AUDITORIAS E INFORMES A ORGANOS FISCALIZADORES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ATENCION DE AUDITORIAS E INFORMES A ORGANOS FISCALIZADORES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'DEPARTAMENTO DE LICITACIONES, ADJUDICACIONES Y CONTRATOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE LICITACIONES, ADJUDICACIONES Y CONTRATOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE OBRAS PUBLICAS' LIMIT 1), 'SUBDIRECCION DE OBRAS DE EQUIPAMIENTO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE OBRAS DE EQUIPAMIENTO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE INSPECCION Y DILIGENCIAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INSPECCION Y DILIGENCIAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'SUBDIRECCION DE OPERACIÓN Y ORDENAMIENTO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE OPERACIÓN Y ORDENAMIENTO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE USO Y CONTROL DEL SUELO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE USO Y CONTROL DEL SUELO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'CENTRO DE INTELIGENCIA TERRITORIAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'CENTRO DE INTELIGENCIA TERRITORIAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'SUBDIRECCION DE PLANEACION TERRITORIAL Y URBANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE PLANEACION TERRITORIAL Y URBANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'ENLACE DE VENTANILLA UNICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE DE VENTANILLA UNICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE CONSTANCIAS, PERMISOS Y LICENCIAS DE CONSTRUCCION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONSTANCIAS, PERMISOS Y LICENCIAS DE CONSTRUCCION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'SUBDIRECCION DE TENENCIA DE LA TIERRA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE TENENCIA DE LA TIERRA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE PREVENCION Y CONTROL DE ASENTAMIENTOS HUMANOS IRREGULARES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PREVENCION Y CONTROL DE ASENTAMIENTOS HUMANOS IRREGULARES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE REGULACION Y REGULARIZACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE REGULACION Y REGULARIZACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE PLANEACION, NORMATIVIDAD Y CONTROL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PLANEACION, NORMATIVIDAD Y CONTROL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'COORDINACION TECNICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION TECNICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'DEPARTAMENTO DE IDENTIDAD E IMAGEN URBANA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE IDENTIDAD E IMAGEN URBANA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION GENERAL DE ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'DIRECCION JURIDICA Y CONSULTIVA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DIRECCION JURIDICA Y CONSULTIVA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE ASUNTOS ADMINISTRATIVOS Y FISCALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ASUNTOS ADMINISTRATIVOS Y FISCALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE BUFETE JURIDICO Y PENAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE BUFETE JURIDICO Y PENAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'SUBDIRECCION DE ASUNTOS INTERNOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE ASUNTOS INTERNOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'SUBDIRECCION DE ASUNTOS EXTERNOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE ASUNTOS EXTERNOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE CONTRATOS Y CONVENIOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE CONTRATOS Y CONVENIOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE CONSULTA, ASESORIA JURIDICA Y REGLAMENTACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE CONSULTA, ASESORIA JURIDICA Y REGLAMENTACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE JUICIOS DE AMPARO Y AGRARIOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE JUICIOS DE AMPARO Y AGRARIOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE ENLACES JURIDICOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ENLACES JURIDICOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE ASUNTOS LABORALES Y CIVILES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ASUNTOS LABORALES Y CIVILES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCION JURIDICA Y CONSULTIVA' LIMIT 1), 'COORDINACION DE ATENCION A OSFEM, CONTRALORIAIA DEL PODER LEGISLATIVO Y CODHEM', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE ATENCION A OSFEM, CONTRALORIAIA DEL PODER LEGISLATIVO Y CODHEM');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'DIRECCIONES' LIMIT 1), 'DESC_ADSCRIPC', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DESC_ADSCRIPC');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'NOVENO REGIDOR' LIMIT 1), 'NOVENO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'NOVENO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OCTAVO REGIDOR' LIMIT 1), 'OCTAVO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'OCTAVO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'COORDINACION GENERAL MUNICIPAL DE MEJORA REGULATORIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION GENERAL MUNICIPAL DE MEJORA REGULATORIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'UNIDAD DE INFORMACION, PLANEACION, PROGRAMACION Y EVALUACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE INFORMACION, PLANEACION, PROGRAMACION Y EVALUACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'SECRETARIA TECNICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SECRETARIA TECNICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'OFICINA DE LA PRESIDENCIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'OFICINA DE LA PRESIDENCIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'COORDINACION DE AGENDA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE AGENDA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'JEFE DE LA OFICINA DE LA PRESIDENCIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'JEFE DE LA OFICINA DE LA PRESIDENCIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'SECRETARIA TECNICA DEL CONSEJO MUNICIPAL DE SEGURIDAD PUBLICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SECRETARIA TECNICA DEL CONSEJO MUNICIPAL DE SEGURIDAD PUBLICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'SECRETARIA PARTICULAR DEL JEFE DE LA OFNA. DE PRESIDENCIA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SECRETARIA PARTICULAR DEL JEFE DE LA OFNA. DE PRESIDENCIA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'OFICINA DE LA PRESIDENCIA' LIMIT 1), 'COORDINACION DE RELACIONES PUBLICAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE RELACIONES PUBLICAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'PRIMER REGIDOR' LIMIT 1), 'PRIMER REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'PRIMER REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'PRIMERA SINDICATURA' LIMIT 1), 'PRIMERA SINDICATURA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'PRIMERA SINDICATURA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'QUINTO REGIDOR' LIMIT 1), 'QUINTO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'QUINTO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'SECRETARIA DEL AYUNTAMIENTO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SECRETARIA DEL AYUNTAMIENTO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE BIENES MUEBLES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BIENES MUEBLES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE OFICIALIAS CALIFICADORAS Y OFICIALIAS MEDIADORAS CONCILIADORAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE OFICIALIAS CALIFICADORAS Y OFICIALIAS MEDIADORAS CONCILIADORAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE BIENES INMUEBLES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE BIENES INMUEBLES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE ARCHIVO MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ARCHIVO MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'OFICIALIA COMUN DE PARTES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'OFICIALIA COMUN DE PARTES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'JUNTA MUNICIPAL DE RECLUTAMIENTO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'JUNTA MUNICIPAL DE RECLUTAMIENTO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE OFICIALIAS DEL REGISTRO CIVIL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE OFICIALIAS DEL REGISTRO CIVIL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE ELABORACION DE ACTAS, ACUERDOS Y CERTIFICACIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ELABORACION DE ACTAS, ACUERDOS Y CERTIFICACIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'SUBSECRETARIA DE GOBIERNO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBSECRETARIA DE GOBIERNO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'SUBSECRETARIA DE APOYO INSTITUCIONAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBSECRETARIA DE APOYO INSTITUCIONAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE MOVILIDAD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MOVILIDAD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'COORDINACION DE PATRIMONIO MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'COORDINACION DE PATRIMONIO MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE APOYO NORMATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE APOYO NORMATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SECRETARIA DEL AYUNTAMIENTO' LIMIT 1), 'DEPARTAMENTO DE MEDIACION Y CONCILIACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MEDIACION Y CONCILIACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SEGUNDA SINDICATURA' LIMIT 1), 'SEGUNDA SINDICATURA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SEGUNDA SINDICATURA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SEGUNDO REGIDOR' LIMIT 1), 'SEGUNDO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SEGUNDO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SEPTIMO REGIDOR' LIMIT 1), 'SEPTIMO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SEPTIMO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'SEXTO REGIDOR' LIMIT 1), 'SEXTO REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SEXTO REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TECNICOS ESPECIALIZADOS' LIMIT 1), 'TECNICOS ESPECIALIZADOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'TECNICOS ESPECIALIZADOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TERCER REGIDOR' LIMIT 1), 'TERCER REGIDOR', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'TERCER REGIDOR');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE IMPUESTOS INMOBILIARIOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE IMPUESTOS INMOBILIARIOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE CAJA GENERAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CAJA GENERAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'ENLACE ADMINISTRATIVO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE ADMINISTRATIVO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE MERCADOS, TIANGUIS Y VIA PUBLICA', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE MERCADOS, TIANGUIS Y VIA PUBLICA');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'TESORERIA MUNICIPAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'TESORERIA MUNICIPAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE ANUNCIOS Y PUBLICIDAD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE ANUNCIOS Y PUBLICIDAD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE CONTABILIDAD', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CONTABILIDAD');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE CATASTRO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CATASTRO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'SUBTESORERIA DE EGRESOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBTESORERIA DE EGRESOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE EJECUCION FISCAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE EJECUCION FISCAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'SUBDIRECCION DE NORMATIVIDAD Y VERIFICACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBDIRECCION DE NORMATIVIDAD Y VERIFICACION');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE PROCEDIMIENTOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE PROCEDIMIENTOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE RECURSOS FEDERALES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE RECURSOS FEDERALES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'ENLACE JURIDICO', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'ENLACE JURIDICO');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE SISTEMAS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE SISTEMAS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'SUBTESORERIA DE INGRESOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'SUBTESORERIA DE INGRESOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE REGISTRO Y CONTROL PRESUPUESTAL', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE REGISTRO Y CONTROL PRESUPUESTAL');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE INGRESOS DIVERSOS', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE INGRESOS DIVERSOS');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE CUENTA PUBLICA Y SOLVENTACIONES', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE CUENTA PUBLICA Y SOLVENTACIONES');
INSERT INTO tm_departamento(depto_id, dep_id, depto_nom, est)
 SELECT NULL, (SELECT COALESCE(dep_id, NULL) FROM tm_dependencia WHERE dep_nom = 'TESORERIA MUNICIPAL' LIMIT 1), 'DEPARTAMENTO DE LICENCIAS, INSPECCION Y VERIFICACION', 1
WHERE NOT EXISTS (SELECT 1 FROM tm_departamento WHERE depto_nom = 'DEPARTAMENTO DE LICENCIAS, INSPECCION Y VERIFICACION');
